---
title: "Venue snapshot analysis"
format: 
  pdf: 
    fig-width: 7
    fig-height: 7
editor: visual
execute:
  echo: FALSE
  warning: FALSE
---

```{r}
# Loading packages
library(dplyr)
library(readxl)
library(ggplot2)
library(ggrepel)
library(tibble)
library(tidyr)
library(labelled)
library(haven)
```

```{r}
# Loading the data
pre_snapshot <- read_sav("../../input/data_processed/pre_snapshot.sav") %>% 
  filter(!City == "")
post_snapshot <- read_sav("../../input/data_processed/post_snapshot.sav") %>%
  rename(City = Q34)
# Reading the captions 
pre_captions <- readxl::read_excel("../../input/other/codebook.xlsx", sheet = 7)
post_captions <- readxl::read_excel("../../input/other/codebook.xlsx", sheet = 8)
```

## Pre-snapshot venue survey analysis

```{r}
# Legal status
pre_snapshot %>%
    count(Q4) %>%
    haven::as_factor() %>%
    na.omit() %>%
    mutate(percentage = n / sum(n) * 100) %>%
    ggplot(aes(x = Q4, y = n)) + geom_bar(stat = "identity", fill = "lightblue") +
    labs(x = "Legal status", y = "Count", title = pre_captions %>%
           filter(question == "Q4") %>%
           select(caption)) +
    geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    vjust = -0.5)
```

```{r}
# Arrengement for the premises
pre_snapshot %>%
  count(Q6) %>%
  haven::as_factor() %>%
  na.omit() %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(y = Q6, x = n)) + geom_bar(stat = "identity", fill = "lightblue") +
  labs(y = "Arrangement", x = "Count", title = pre_captions %>%
           filter(question == "Q6") %>%
           select(caption)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    vjust = -0.5) 
```

```{r}
# Year of establishment
pre_snapshot %>%
    ggplot(aes(x = Q7)) + geom_histogram() + 
    labs(x = "Year", title = pre_captions %>%
           filter(question == "Q7") %>%
           select(caption)) +
    scale_x_continuous(breaks = seq(1925, 2025, 10), lim = c(1925, 2025)) +
    scale_y_continuous(breaks = seq(0, 10, 2), lim = c(0,10))
```

```{r}
# What days the venue is open
pre_snapshot %>%
  select(starts_with("Q8"), City) %>%
  haven::as_factor() %>% 
  pivot_longer(!City, names_to = "question", values_to = "value") %>%
  na.omit %>%
  count(value) %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(y = value, x = n)) + 
  geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Count", y = "Weekday", title = pre_captions %>%
           filter(question == "Q8") %>%
           select(caption)) +
  scale_y_discrete(labels = scales::label_wrap(50)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                  hjust = -0.2) 
```

```{r}
# What months is the venue open?
pre_snapshot %>%
  select(starts_with("Q9"), City) %>%
  haven::as_factor() %>% 
  pivot_longer(!City, names_to = "question", values_to = "value") %>%
  na.omit %>%
  count(value) %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(y = value, x = n)) + 
  geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Count", y = "Month", title = pre_captions %>%
           filter(question == "Q9") %>%
           select(caption)) +
  scale_y_discrete(labels = scales::label_wrap(50)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                  hjust = -0.2) 
```

```{r}
# How would you descripe the venue
pre_snapshot %>%
    count(Q10) %>%
    haven::as_factor() %>%
    na.omit() %>% 
    mutate(percentage = n / sum(n) * 100) %>%
    ggplot(aes(y = Q10, x = n)) + geom_bar(stat = "identity", fill = "lightblue") +
    labs(x = "Count", y = "Description",
         title = pre_captions %>%
           filter(question == "Q10") %>%
           select(caption)) +
    scale_y_discrete(labels = scales::label_wrap(50)) +
    geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    hjust = -0.2) 
```

```{r}
# Venue capacity
pre_snapshot %>%
    count(Q11) %>%
    haven::as_factor() %>%
    na.omit() %>% 
    mutate(percentage = n / sum(n) * 100) %>%
    ggplot(aes(y = Q11, x = n)) + geom_bar(stat = "identity", fill = "lightblue") +
    labs(x = "Count", y = "Capacity",
         title = pre_captions %>%
           filter(question == "Q11") %>%
           select(caption)) +
    scale_y_discrete(labels = scales::label_wrap(50)) +
    geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    hjust = -0.2) 
```

```{r}
# Venue activities 
pre_snapshot %>%
  select(starts_with("Q12"), City) %>%
  haven::as_factor() %>% 
  pivot_longer(!City, names_to = "question", values_to = "value") %>%
  na.omit %>%
  count(value) %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(y = value, x = n)) + 
  geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Count", y = "Activity", title = pre_captions %>%
           filter(question == "Q12") %>%
           select(caption)) +
  scale_y_discrete(labels = scales::label_wrap(50)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                  hjust = -0.2) 
```

```{r}
# Will you hold a live music
pre_snapshot %>%
  count(Q13) %>%
  haven::as_factor() %>%
  na.omit() %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(x = Q13, y = n)) + geom_bar(stat = "identity", fill = "lightblue") +
  labs( x = "Anwser", y = "Count", title = pre_captions %>%
           filter(question == "Q13") %>%
           select(caption)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    vjust = -0.5) 
```

```{r}
# Is your venue negatively affected by the following
pre_snapshot %>%
  select(starts_with("Q14"), City) %>%
  select(-Q14_15_TEXT) %>%
  haven::as_factor() %>% 
  pivot_longer(!City, names_to = "question", values_to = "value") %>%
  na.omit %>%
  count(value) %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(y = value, x = n)) + 
  geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Count", y = "Reason", title = pre_captions %>%
           filter(question == "Q14") %>%
           select(caption)) +
  scale_y_discrete(labels = scales::label_wrap(50)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                  hjust = -0.2) 
```

```{r}
# Enviromentally friendly
pre_snapshot %>%
  count(Q15_1) %>%
  haven::as_factor() %>%
  na.omit() %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(x = Q15_1, y = n)) + geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Answer", y = "Count", title = pre_captions %>%
           filter(question == "Q15_1") %>%
           select(caption)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    vjust = -0.5) 
```

```{r}
# Discrimination
pre_snapshot %>%
  count(Q15_2) %>%
  haven::as_factor() %>%
  na.omit() %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(x = Q15_2, y = n)) + geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Answer", y = "Count", title = pre_captions %>%
           filter(question == "Q15_2") %>%
           select(caption)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    vjust = -0.5) 
```

```{r}
# Corruption
pre_snapshot %>%
  count(Q15_3) %>%
  haven::as_factor() %>%
  na.omit() %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(x = Q15_3, y = n)) + geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Answer", y = "Count", title = pre_captions %>%
           filter(question == "Q15_3") %>%
           select(caption)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    vjust = -0.5) 
```

```{r}
# Optimism
pre_snapshot %>%
  count(Q18) %>%
  haven::as_factor() %>%
  na.omit() %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(x = Q18, y = n)) + geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Answer", y = "Count", title = pre_captions %>%
           filter(question == "Q18") %>%
           select(caption)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    vjust = -0.5)
```

## Post-snapshot venue survey analysis

```{r}
# Venue location
post_snapshot %>%
  count(City) %>%
  haven::as_factor() %>%
  na.omit() %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(x = City, y = n)) + geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Location", y = "Count", title = post_captions %>%
           filter(question == "City") %>%
           select(caption)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    vjust = -0.5)
```

```{r}
# Did you host live music event 
post_snapshot %>%
  count(Q1, City) %>%
  haven::as_factor() %>%
  na.omit() %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(x = Q1, y = n)) + geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Answer", y = "Count", title = post_captions %>%
           filter(question == "Q1") %>%
           select(caption)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    vjust = -0.5) + facet_wrap(vars(City))
```

```{r}
# How many live music events did you host
post_snapshot %>%
  count(Q2, City) %>%
  haven::as_factor() %>%
  na.omit() %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(x = Q2, y = n)) + geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Amount", y = "Count", title = post_captions %>%
           filter(question == "Q2") %>%
           select(caption)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    vjust = -0.5) + facet_wrap(vars(City))
```

```{r}
# Average how many days stage live music
post_snapshot %>%
  count(Q4, City) %>%
  haven::as_factor() %>%
  na.omit() %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(y = Q4, x = n)) + geom_bar(stat = "identity", fill = "lightblue") +
  labs(y = "Amount", x = "Count", title = post_captions %>%
           filter(question == "Q4") %>%
           select(caption)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    hjust = -0.2) + facet_wrap(vars(City))
```

```{r}
# Attendance compared to before COVID
post_snapshot %>%
  count(Q6, City) %>%
  haven::as_factor() %>%
  na.omit() %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(x = Q6, y = n)) + geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Answer", y = "Count", title = post_captions %>%
           filter(question == "Q6") %>%
           select(caption)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    vjust = 0.5) + facet_wrap(vars(City))
```

```{r}
# Before full-scale Russian assault
post_snapshot %>%
  haven::as_factor() %>%
  filter(City == "Lviv") %>%
  count(Q7) %>%
  na.omit() %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(x = Q7, y = n)) + geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Answer", y = "Count", title = post_captions %>%
           filter(question == "Q7")) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                    vjust = 0.2)
```

```{r, fig.width=8, fig.height=8}
# What kinds of live music genre most often present
post_snapshot %>%
  select(starts_with("Q8"), City) %>%
  haven::as_factor() %>% 
  pivot_longer(!City, names_to = "question", values_to = "value") %>%
  na.omit %>%
  count(value, City) %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(y = value, x = n)) + 
  geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Count", y = "Genre", title = post_captions %>%
           filter(question == "Q8") %>%
           select(caption)) +
  scale_y_discrete(labels = scales::label_wrap(50)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                  hjust = -0.2) + facet_wrap(vars(City))
```

```{r}
# Event entrance
post_snapshot %>%
  select(starts_with("Q9"), City) %>%
  haven::as_factor() %>% 
  pivot_longer(!City, names_to = "question", values_to = "value") %>%
  na.omit %>%
  count(value, City) %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(y = value, x = n)) + 
  geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Count", y = "Fee type", title = post_captions %>%
           filter(question == "Q9") %>%
           select(caption)) +
  scale_y_discrete(labels = scales::label_wrap(50)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                  hjust = -0.2) + facet_wrap(vars(City))
```

```{r}
# Event organizers
post_snapshot %>%
    count(Q10, City) %>%
    haven::as_factor() %>%
    na.omit() %>%
    mutate(percentage = n / sum(n) * 100) %>%
    ggplot(aes(y = Q10, x = n)) + 
    geom_bar(stat = "identity", fill = "lightblue") +
    labs(x = "Count", y = "Organizer", title = post_captions %>%
           filter(question == "Q10") %>%
           select(caption)) +
    scale_y_discrete(labels = scales::label_wrap(50)) + facet_wrap(vars(City)) +
    scale_x_continuous(breaks = seq(0,13,2))
```

```{r}
# How do you pay the performers
post_snapshot %>%
  select(starts_with("Q12"), City) %>%
  haven::as_factor() %>% 
  pivot_longer(!City, names_to = "question", values_to = "value") %>%
  na.omit %>%
  count(value, City) %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(y = value, x = n)) + 
  geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Count", y = "Pay type", title = post_captions %>%
           filter(question == "Q12") %>%
           select(caption)) +
  scale_y_discrete(labels = scales::label_wrap(50)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                  hjust = -0.2) + facet_wrap(vars(City))
```

```{r}
# Music festivals
post_snapshot %>%
    count(Q13, City) %>%
    haven::as_factor() %>%
    na.omit() %>%
    mutate(percentage = n / sum(n) * 100) %>%
    ggplot(aes(y = Q13, x = n)) + 
    geom_bar(stat = "identity", fill = "lightblue") +
    labs(x = "Count", y = "Answer", title = post_captions %>%
           filter(question == "Q13") %>%
           select(caption)) +
    scale_y_discrete(labels = scales::label_wrap(50)) + facet_wrap(vars(City)) +
    scale_x_continuous(breaks = seq(0,13,2))
```

```{r}
# Staff composition
post_snapshot %>%
  select(starts_with("Q14"), City) %>%
  haven::as_factor() %>% 
  pivot_longer(!City, names_to = "question", values_to = "value") %>%
  na.omit %>%
  count(value, City) %>%
  mutate(percentage = n / sum(n) * 100) %>%
  ggplot(aes(y = value, x = n)) + 
  geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "Count", y = "Staff type", title = post_captions %>%
           filter(question == "Q14") %>%
           select(caption)) +
  scale_y_discrete(labels = scales::label_wrap(50)) +
  geom_text_repel(aes(label = paste0(n, " (", round(percentage, 1), "%)")),
                  hjust = -0.2) + facet_wrap(vars(City))
```

```{r}
# Total anual revenue
# options(scipen = 999)
# post_snapshot %>%
#   select(Q34, Q25) %>%
#   filter(Q34 == "Helsinki") %>%
#   na.omit() %>%
#   ggplot(aes(x = Q25)) + geom_histogram() + facet_wrap(vars(Q34)) +
#   labs(title = "Total anual revenue")
```
